### login employee
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "password": "employeeA!#22",
  "phone": "+201058854455"
}


### login admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "password": "StrongPass1@",
  "phone": "+201503657687"
}