### beneficiaries-signup
POST http://localhost:5000/api/auth/beneficiaries-signup
Content-Type: application/json

{
  "name": "Ziad Zayed",
  "email": "ziadzayd79@gmail.com",
  "password": "StrongPass1@",
  "phone": "+201503657687",
  "account_type": "organization",
  "organization_name": "org1",
  "organization_type": "nursery"
}
### enrichers-signup
POST http://localhost:5000/api/auth/enrichers-signup
Content-Type: application/json

{
  "name": "Ziad Zayed",
  "email": "zIffsfffAD.TEfffSfT@GMAIL.COM",
  "password": "StrongPass1@",
  "phone": "+201055084375",
  "accountType": "organization",
  "organizationName": "enricher"
}

### enrichers-signup
POST http://localhost:5000/api/auth/enrichers-signup
Content-Type: application/json

{
  "name": "Admin",
  "email": "Admin@Admin.com",
  "password": "StrongPass1@",
  "phone": "+201280841070",
  "accountType": "organization",
  "organizationName": "enricher"
}