
GET http://localhost:5000/api/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZTYwNDU5NS1iNDU3LTRiNzgtYjE1OS05N2Y1M2Q2ZWUxMzIiLCJpYXQiOjE3NzQ4NzYzNTAsImV4cCI6MTc3NDk2Mjc1MH0.wPQFKy8HxId48eo0lLnOt9iFcFPmLHTrB3DLVmHAmVA