
GET http://localhost:5000/children/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2U4ZmJmYS1lNDdkLTRiYWEtYTU2Mi1lMjY1ZTQwYjk0NDEiLCJlbWFpbCI6InppZmZzZmZmYWQudGVmZmZzZnRAZ21haWwuY29tIiwicGhvbmUiOiIrMjAxMDU1MDg0Mzc1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzczMTU3NzY3LCJleHAiOjE3NzU3NDk3Njd9.RTkpcwoeWRJmU6bvn9lHUbFBtP_4KxCq7saGj6HmMzQ

