
GET http://localhost:5000/children?userId=e2387e09-8e8f-4778-b177-efa9272d794e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjM4N2UwOS04ZThmLTQ3NzgtYjE3Ny1lZmE5MjcyZDc5NGUiLCJlbWFpbCI6ImVtcGx5ZWVAdGVzc3QuY29tIiwicGhvbmUiOiIrMjAxMDU4ODU0NDU1Iiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNzczMTU3ODg0LCJleHAiOjE3NzU3NDk4ODR9.NaIGzQxGR-AhFZ8E1VbzbKHWiaQQH0Iw9udq5iudG3U

