DELETE http://localhost:5000/children/0cd0ce64-97b4-486e-b1e0-2eee1e6f48d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjM4N2UwOS04ZThmLTQ3NzgtYjE3Ny1lZmE5MjcyZDc5NGUiLCJlbWFpbCI6ImVtcGx5ZWVAdGVzc3QuY29tIiwicGhvbmUiOiIrMjAxMDU4ODU0NDU1Iiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNzczMTU3ODg0LCJleHAiOjE3NzU3NDk4ODR9.NaIGzQxGR-AhFZ8E1VbzbKHWiaQQH0Iw9udq5iudG3U
