
GET http://localhost:5000/api/employees/organization/93c4b384-4f2b-46b1-bafe-b2f560b05bdd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2U4ZmJmYS1lNDdkLTRiYWEtYTU2Mi1lMjY1ZTQwYjk0NDEiLCJlbWFpbCI6InppZmZzZmZmYWQudGVmZmZzZnRAZ21haWwuY29tIiwicGhvbmUiOiIrMjAxMDU1MDg0Mzc1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcyOTY5MjQwLCJleHAiOjE3NzI5NzAxNDB9.OVqTQdPFUtbW2AK_EJduGxzJ0WD7uEy3ZUT4zIgmWlo

