
GET http://localhost:5000/api/employees/069cf905-0beb-4db5-9cbf-92712300ea81
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2U4ZmJmYS1lNDdkLTRiYWEtYTU2Mi1lMjY1ZTQwYjk0NDEiLCJlbWFpbCI6InppZmZzZmZmYWQudGVmZmZzZnRAZ21haWwuY29tIiwicGhvbmUiOiIrMjAxMDU1MDg0Mzc1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcyOTY5MjQwLCJleHAiOjE3NzI5NzAxNDB9.OVqTQdPFUtbW2AK_EJduGxzJ0WD7uEy3ZUT4zIgmWlo

