
GET http://localhost:5000/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2U4ZmJmYS1lNDdkLTRiYWEtYTU2Mi1lMjY1ZTQwYjk0NDEiLCJlbWFpbCI6InppZmZzZmZmYWQudGVmZmZzZnRAZ21haWwuY29tIiwicGhvbmUiOiIrMjAxMDU1MDg0Mzc1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcyOTY3Njc3LCJleHAiOjE3NzI5Njg1Nzd9.6EdpS6Zc9zIPBtsULMLTiM5prZKxzEyzMYgzVJaOUko

